# Generated by Django 5.0 on 2024-12-15 17:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=15, unique=True)),
                ('last_name', models.CharField(max_length=15, unique=True)),
                ('tel_number', models.CharField(max_length=15, unique=True)),
                ('car', models.CharField(max_length=30, unique=True)),
                ('car_number', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(default='Неизвестно', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('city', models.CharField(choices=[('Айдаркен', 'Айдаркен'), ('Базар-Коргон', 'Базар-Коргон'), ('Балыкчы', 'Балыкчы'), ('Баткен', 'Баткен'), ('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Кадамжай', 'Кадамжай'), ('Каинды', 'Каинды'), ('Кант', 'Кант'), ('Кара-Балта', 'Кара-Балта'), ('Каракол', 'Каракол'), ('Кара-Куль', 'Кара-Куль'), ('Кара-Суу', 'Кара-Суу'), ('Кемин', 'Кемин'), ('Кербен', 'Кербен'), ('Кок-Джангак', 'Кок-Джангак'), ('Кочкор-Ата', 'Кочкор-Ата'), ('Кызыл-Кия', 'Кызыл-Кия'), ('Майлуу-Суу', 'Майлуу-Суу'), ('Нарын', 'Нарын'), ('Ноокат', 'Ноокат'), ('Орловка', 'Орловка'), ('Ош', 'Ош'), ('Раззаков', 'Раззаков'), ('Сулюкта', 'Сулюкта'), ('Талас', 'Талас'), ('Таш-Кумыр', 'Таш-Кумыр'), ('Токмак', 'Токмак'), ('Токтогул', 'Токтогул'), ('Узген', 'Узген'), ('Чолпон-Ата', 'Чолпон-Ата'), ('Шопоков', 'Шопоков'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=25, null=True)),
                ('user_description', models.CharField(blank=True, default=' Рабочий день: ПН-ВС \n Время работы: 08:00-23:00 \n Адресс: ул. Ленина 55 ', max_length=500, null=True)),
                ('user_phone_number', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('user_phone_number2', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('user_mbank_qr', models.ImageField(blank=True, null=True, upload_to='static/media/user/logo/')),
                ('user_rsk_qr', models.ImageField(blank=True, null=True, upload_to='static/media/user/logo/')),
                ('user_raiting', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('category_of_education', models.CharField(blank=True, choices=[('Food', 'Еда'), ('Vegetables', 'Овощи'), ('Shop', 'Магазин')], default='Dining_room', max_length=20, null=True)),
                ('sub_category_of_education', models.CharField(blank=True, choices=[('Grocery', 'Продуктовый'), ('Vegetables', 'Электроника'), ('Clothes', 'Одежды'), ('Office', 'Канцелярия')], max_length=20, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Online', 'Онлайн'), ('Offline', 'Оффлайн')], default='Online', max_length=20, null=True)),
                ('user_logo', models.ImageField(blank=True, null=True, upload_to='static/media/user/logo/')),
                ('user_logo_mini', models.ImageField(blank=True, null=True, upload_to='static/media/user/logo/')),
                ('user_blocked', models.CharField(choices=[('Yes', 'Да'), ('No', 'Нет')], default='No', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
