# Generated by Django 5.0 on 2024-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category_of_education',
            field=models.CharField(blank=True, choices=[('Food', 'Еда'), ('Vegetables', 'Овощи'), ('Shop', 'Магазин')], default='Food', max_length=20, null=True),
        ),
    ]
