# Generated by Django 5.0 on 2024-12-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_category_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_category_of_education',
            field=models.CharField(blank=True, choices=[('', ''), ('Grocery', 'Продуктовый'), ('Vegetables', 'Электроника'), ('Clothes', 'Одежды'), ('Office', 'Канцелярия')], default='', max_length=20, null=True),
        ),
    ]
