# Generated by Django 5.0 on 2024-12-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_secondaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
