# Generated by Django 5.0 on 2024-12-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_secondaryuser_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondaryUser',
        ),
    ]
