# Generated by Django 5.0 on 2024-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_secondaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ordinary_user', 'обычный_пользователь'), ('food_user', 'пользователь_еда'), ('shop_user', 'пользователь_магазин'), ('taxi_user', 'пользователь_такси'), ('courier_user', 'пользователь_курьер'), ('taxi_company_user', 'пользователь_таксопарк')], default='ordinary_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='category_of_education',
            field=models.CharField(blank=True, choices=[('', ''), ('Food', 'Еда'), ('Vegetables', 'Овощи'), ('Shop', 'Магазин')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_blocked',
            field=models.CharField(choices=[('', ''), ('Yes', 'Да'), ('No', 'Нет')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(blank=True, choices=[('', ''), ('Online', 'Онлайн'), ('Offline', 'Оффлайн')], default='', max_length=20, null=True),
        ),
    ]
