# Generated by Django 5.0 on 2025-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_balance_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('sms_code', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
