# Generated by Django 5.0 on 2025-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_blocked',
            field=models.CharField(choices=[('', ''), ('Yes', 'Да'), ('No', 'Нет')], default='No', max_length=20),
        ),
    ]
