# Generated by Django 5.0 on 2025-01-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_user_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ordinary_user', 'обычный пользователь'), ('food_user', 'пользователь еда'), ('shop_user', 'пользователь магазин'), ('taxi_user', 'Водитель такси'), ('courier_user', 'Водитель курьер'), ('taxi_company_user', 'Владелец таксопарк')], default='ordinary_user', max_length=20),
        ),
    ]
