# Generated by Django 5.0 on 2025-10-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'rated_by')},
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user'], name='account_use_user_id_14b8ed_idx'),
        ),
    ]
