# Generated by Django 5.0 on 2025-10-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userrating_updated_at_alter_userrating_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_abank_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_mbank_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_obank_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_rsk_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
