# Generated by Django 5.0 on 2025-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_user_abank_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_abank_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_mbank_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_obank_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_rsk_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
