# Generated by Django 5.0 on 2025-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuser_user_abank_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ordinary_user', 'Обычный пользователь'), ('food_user', 'Пользователь еда'), ('shop_user', 'Пользователь магазин'), ('taxi_user', 'Водитель такси'), ('courier_user', 'Водитель курьер'), ('taxi_company_user', 'Владелец таксопарк')], default='ordinary_user', max_length=20),
        ),
    ]
