# Generated by Django 5.0 on 2026-02-08 19:01

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_logo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_logo_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_logo_mini',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_logo_mini_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_mbank_qr',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_mbank_qr_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_rsk_qr',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_rsk_qr_path),
        ),
    ]
