# Generated by Django 5.0 on 2024-12-15 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_first_name', models.CharField(blank=True, max_length=15)),
                ('courier_last_name', models.CharField(blank=True, max_length=15)),
                ('courier_tel_number', models.CharField(blank=True, max_length=15)),
                ('courier_car', models.CharField(blank=True, max_length=40)),
                ('courier_car_number', models.CharField(blank=True, max_length=15)),
                ('courier_status', models.CharField(choices=[('expectation', 'Ожидание'), ('called', 'Вызываем курьера'), ('pick_up', 'Забирает заказ'), ('on_the_way', 'В пути'), ('delivered', 'Доставлено'), ('canceled', 'Отменено')], default='expectation', max_length=30)),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_user_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_details', models.TextField()),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Успешно'), ('cancelled', 'Отменен')], default='in_progress', max_length=20)),
                ('order_tel_number', models.CharField(max_length=14)),
                ('order_adsress', models.CharField(max_length=100)),
                ('order_bank_check', models.ImageField(blank=True, null=True, upload_to='static/media/orders_bank_check')),
                ('order_payment_status', models.CharField(max_length=100)),
                ('order_delivery_status', models.CharField(max_length=100)),
                ('order_city', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('price', models.DecimalField(decimal_places=0, default='10', max_digits=10)),
                ('food_status', models.CharField(choices=[('True', 'В наличии'), ('False', 'Отсутствует')], default='True', max_length=20)),
                ('adscreenimg', models.ImageField(upload_to='static/media/foodimages/foodimg')),
                ('imageOne', models.ImageField(upload_to='static/media/foodimages')),
                ('date_add', models.DateField(blank=True, null=True)),
                ('click_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='basis.foodcategory')),
            ],
        ),
    ]
