# Generated by Django 5.0 on 2024-12-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
