# Generated by Django 5.0 on 2024-12-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0002_rename_name_foodcategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
