# Generated by Django 5.0 on 2025-10-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0005_userfirebasetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFirebaseToken',
        ),
    ]
