# Generated by Django 5.0 on 2026-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_menu',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_menu',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
