# Generated by Django 5.0 on 2026-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0009_food_menu_discount_active_food_menu_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_menu',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
