# Generated by Django 5.0 on 2026-02-08 19:01

import basis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0010_food_menu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_menu',
            name='adscreenimg',
            field=models.ImageField(upload_to=basis.models.ad_screen_img_path),
        ),
        migrations.AlterField(
            model_name='food_menu',
            name='imageOne',
            field=models.ImageField(upload_to=basis.models.food_image_one_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_bank_check',
            field=models.ImageField(blank=True, null=True, upload_to=basis.models.order_bank_check_path),
        ),
    ]
