# Generated by Django 5.0 on 2026-02-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0011_alter_food_menu_adscreenimg_alter_food_menu_imageone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('accept', 'Принято'), ('completed', 'Успешно'), ('cancelled', 'Отменен')], default='in_progress', max_length=20),
        ),
    ]
