# Generated by Django 5.0 on 2026-02-22 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_del', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], default='economy', max_length=20, verbose_name='Класс авто'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление координат'),
        ),
        migrations.AddField(
            model_name='driver',
            name='online_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Вышел на линию'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='driver',
            name='trips_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество поездок'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bank_link',
            field=models.URLField(blank=True, help_text='MBank, Optima и т.д.', null=True, verbose_name='Ссылка на оплату/банк'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Администратор может забанить водителя', verbose_name='Проверен/Активен'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='role',
            field=models.CharField(choices=[('taxi', 'Такси'), ('delivery', 'Доставка'), ('both', 'Такси и Доставка')], default='taxi', max_length=20, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Свободен (на линии)'), ('busy', 'Занят (на заказе)')], default='offline', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(max_length=100, verbose_name='Марка и модель'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(max_length=20, verbose_name='Гос. номер'),
        ),
        migrations.CreateModel(
            name='OrderTaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('order_type', models.CharField(choices=[('taxi', 'Такси'), ('delivery', 'Доставка')], default='taxi', max_length=20, verbose_name='Тип')),
                ('car_class', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], default='economy', max_length=20, verbose_name='Класс авто')),
                ('status', models.CharField(choices=[('pending', 'Ожидание (поиск водителя)'), ('accepted', 'Принят водителем'), ('on_way', 'Водитель едет к клиенту'), ('arrived', 'Водитель на месте'), ('in_progress', 'В пути с клиентом'), ('completed', 'Завершен'), ('canceled', 'Отменен')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='Адрес подачи')),
                ('pickup_latitude', models.FloatField(verbose_name='Широта подачи')),
                ('pickup_longitude', models.FloatField(verbose_name='Долгота подачи')),
                ('destination_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес назначения')),
                ('destination_latitude', models.FloatField(blank=True, null=True, verbose_name='Широта назначения')),
                ('destination_longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота назначения')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('tips', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чаевые')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта (онлайн)'), ('wallet', 'Личный баланс')], default='cash', max_length=10, verbose_name='Тип оплаты')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Расстояние (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принят водителем')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Водитель прибыл')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Поездка началась')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Поездка завершена')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменен')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='Доп. данные (товары, опции)')),
                ('external_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Внешний ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка клиента')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='Отзыв клиента')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_orders', to='taxi_del.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заказы такси',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Order_taxi',
        ),
    ]
