# Generated by Django 5.0 on 2026-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_del', '0002_alter_driver_options_driver_balance_driver_car_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertaxi',
            name='excluded_drivers',
            field=models.ManyToManyField(blank=True, related_name='excluded_orders', to='taxi_del.driver'),
        ),
    ]
