# Generated by Django 5.0 on 2026-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_del', '0003_ordertaxi_excluded_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_class',
            field=models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], default='econom', max_length=20, verbose_name='Класс авто'),
        ),
    ]
