# Generated by Django 5.0 on 2026-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_del', '0005_alter_ordertaxi_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertaxi',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='search_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
