# Generated by Django 5.0 on 2026-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_del', '0006_ordertaxi_offered_at_ordertaxi_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertaxi',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='ordertaxi',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дистанция'),
        ),
    ]
